linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-rules:
    # Generated files do not need lint checks.
    - path: gen/
      linters:
        - all
